### ISSUE TITLE
host data volumes not writable by container

### ISSUE THREAD

**Issue by tomdavidson** [docker/kitematic#593]
I previously thought I needed help using compose: https://github.com/docker/compose/issues/1505 but my docker-compose.yml works just fine on my Linux host even though it fails consistently with Kitematic.

The problem is permission relate when using host for data volumes for database storage as described here: http://stackoverflow.com/questions/30624186/database-fails-to-start-host-directory-as-a-data-volume

Working on Linux is good for me, but I need a solution for my OSX co-workers. Is there a kitematic compatible way to do:
```
db:
  image: mariadb
  expose: 
   - "3306"
  volumes: 
   - ../containers/expressionengine/var-lib-mysql/:/var/lib/mysql
```

**Comment by TeckniX** [comment]
The answer is actually found here:
https://docs.docker.com/userguide/dockervolumes/#mount-a-host-directory-as-a-data-volume

The only volumes that can be mounted are under the `/Users` directory. 
If you updated your config to be something like:
```
db:
  image: mariadb
  expose: 
   - "3306"
  volumes: 
   - /Users/<path>/expressionengine/var-lib-mysql/:/var/lib/mysql
```
then it should work

**Comment by tomdavidson** [comment]
sorry i was not clear with my post - the relative path is in the /Users dir and the symptoms are the same with $PWD/....../var-lib-mysql and with /Users/<path>/

**Comment by TeckniX** [comment]
debian and kubuntu wouldn't have the issue, since there are no VM running -  What docker file are you using? I'd like to replicate the setup and see the errors being generated. 
Did you try to set the permissions as explained in the previous SO link? If you login to the VM (not the container) can you see the files? What permissions do they have?

**Comment by tomdavidson** [comment]
exactly, something is off in the vm container config. I can reproduce with a docker compose file that only consists of the following:
```
expressionengine:
  image: mariadb
  expose: 
   - "3306"
  volumes:
   - $PWD/containers/expressionengine/var-lib-mysql/:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=expressionengine
  ```
Perms from SO: I do not want host mapped data volumes defined a db container. Im ok with docker-compose.yml not being portable, but I want to be as generic as possible with the containers. Once I tried it on Linux I was able to confirm Im not doing it 'wrong', but that something is broken with kitematic.
